### ISSUE TITLE
Error Message on openWB over MQTT integration

### ISSUE THREAD

**Issue by Schtallone** [a529987659852/openwb2mqtt#18]
I am rarely new in the home assistant communitiy and since about 1-2 month, I am running HA on a Intel NUC as OS installation. All parts of HA are up to date.

For my ev-charger from openWB, I installed this integration.

I don’t now since, but I recieve an error message out of the Log in HA, without having any functional issues with the integration itserlf. But I want to have a clear log ;-).

Here is the error message, which comes every few seconds:

`Exception in message_received when handling msg on 'openWB/chargepoint/5/get/connected_vehicle/config': '{"average_consumption": 13000, "charge_template": 0, "chargemode": "pv_charging", "current_plan": null, "ev_template": 0, "priority": false, "time_charging_in_use": false}' Traceback (most recent call last): File "/config/custom_components/openwb2mqtt/select.py", line 102, in message_received message.payload = self.entity_description.value_fn(message.payload) ^^^^^^^^^^^^^^^ File "<string>", line 4, in __setattr__ dataclasses.FrozenInstanceError: cannot assign to field 'payload' `

Is there anybody who can help me solving this error?

Thank you in advance and greetings
Peter

**Comment by schariwari** [comment]
Exact the same here, every 10sec:

`2024-05-24 13:25:57.967 ERROR (MainThread) [homeassistant.util.logging] Exception in message_received when handling msg on 'openWB/chargepoint/1/get/connected_vehicle/config': '{"average_consumption": 17000, "charge_template": 0, "chargemode": "pv_charging", "current_plan": null, "ev_template": 0, "priority": false, "time_charging_in_use": false}'
Traceback (most recent call last):
  File "/config/custom_components/openwb2mqtt/select.py", line 102, in message_received
    message.payload = self.entity_description.value_fn(message.payload)
    ^^^^^^^^^^^^^^^
  File "<string>", line 4, in __setattr__
dataclasses.FrozenInstanceError: cannot assign to field 'payload'
`

any hint would be helpful!

**Comment by schariwari** [comment]
![Bildschirmfoto 2024-05-24 um 14 10 00](https://github.com/a529987659852/openwb2mqtt/assets/11351987/258c550f-dcad-4dca-baf4-454fbf33f417)

Seems to happen pretty often....

**Comment by heiru2011** [comment]
Gleicher Fehler auch bei mir ohne Funktionseinschränkungen:

Logger: homeassistant.util.logging
Quelle: util/logging.py:98
Erstmals aufgetreten: 22:50:03 (148 Vorkommnisse)
Zuletzt protokolliert: 22:56:01

Exception in message_received when handling msg on 'openWB/chargepoint/8/get/connected_vehicle/config': '{"average_consumption": 15000, "charge_template": 1, "chargemode": "pv_charging", "current_plan": null, "ev_template": 1, "priority": true, "time_charging_in_use": false}' Traceback (most recent call last): File "/config/custom_components/openwb2mqtt/select.py", line 102, in message_received message.payload = self.entity_description.value_fn(message.payload) ^^^^^^^^^^^^^^^ File "<string>", line 4, in __setattr__ dataclasses.FrozenInstanceError: cannot assign to field 'payload'
Exception in message_received when handling msg on 'openWB/chargepoint/14/get/connected_vehicle/config': '{"average_consumption": 16000, "charge_template": 2, "chargemode": "pv_charging", "current_plan": null, "ev_template": 2, "priority": false, "time_charging_in_use": false}' Traceback (most recent call last): File "/config/custom_components/openwb2mqtt/select.py", line 102, in message_received message.payload = self.entity_description.value_fn(message.payload) ^^^^^^^^^^^^^^^ File "<string>", line 4, in __setattr__ dataclasses.FrozenInstanceError: cannot assign to field 'payload'

**Comment by schariwari** [comment]
Thanks a lot!
