### ISSUE TITLE
Discussion: How to trigger changes in openwb2 via MQTT

### ISSUE THREAD

**Issue by a529987659852** [a529987659852/openwb2mqtt#2]
Dear all,

I haven't yet figured out how to trigger changes from Home Assistant to the Wallbox, version 2.
For example, I'd like to change from PV --> Sofortladen charge mode.
I figured out that the chargepoint seems to be connected to a charge profile and the latter must be changed. However, I'm, not sure whether this is correct.

If you already have some insights, please share here so that I don't have to work from scratch.

Thank you very much
Andreas

**Comment by EckeFL** [comment]
Hmpf....
Change Chargemode dosn´t work on an openWB pro
![mqtt chargemode](https://github.com/a529987659852/openwb2mqtt/assets/50829150/0a16ae80-ab55-4388-9a69-fc568343979e)
