### ISSUE TITLE
async_forward_entry_setup issue, integration will stop working in Home Assistant 2025.1

### ISSUE THREAD

**Issue by Bascht74** [a529987659852/openwb2mqtt#20]
Logger: homeassistant.helpers.frame
Quelle: helpers/frame.py:151
Erstmals aufgetreten: 17:38:45 (22 Vorkommnisse)
Zuletzt protokolliert: 17:38:46

Detected code that calls async_forward_entry_setup for integration openwb2mqtt with title: openWB Ladepunkt rechts and entry_id: 1fd48b199d8b15eae04633e4940d5923, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Detected code that calls async_forward_entry_setup for integration openwb2mqtt with title: openWB and entry_id: 57d08cdb74de7ade1ebe74e4e7d30a54, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Detected code that calls async_forward_entry_setup for integration openwb2mqtt with title: PV and entry_id: 01J5K0DNC6PD6CKYTNMQTX1W8A, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Detected code that calls async_forward_entry_setup for integration openwb2mqtt with title: Virtueller Zähler and entry_id: 01J5K0GSAR3WRFWGWFDSY9GRSA, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Detected code that calls async_forward_entry_setup for integration openwb2mqtt with title: Hauszähler and entry_id: 01J5K0J43WZ7XFRFZ0K0CZ7JJG, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

**Comment by a529987659852** [comment]
Thanks for raising the issue.
Already solved with PR 880f738.
Will be included in the next release.

Andreas
