### ISSUE TITLE
Device Icons missing 

### ISSUE THREAD

**Issue by EckeFL** [a529987659852/openwb2mqtt#5]
In der Geräteübersicht werden keine Icons für die Geräte Angezeigt 
![Screenshot_2024-01-05-00-11-13-881_io homeassistant companion android](https://github.com/a529987659852/openwb2mqtt/assets/50829150/cbc94dd9-eea8-4cfa-8b27-326d290dd51c)

**Comment by a529987659852** [comment]
https://github.com/home-assistant/brands/pull/5066
