### ISSUE TITLE
Ladestromvorgabe needs multiplication by 10

### ISSUE THREAD

**Issue by boredomwontgetus** [a529987659852/openwb2mqtt#6]
Hi!

Looks like the entity "Ladestromvorgabe" is divided by 10. 

Setting it to 6A on the WB itself produces a value of 0.6 in the entity. 
7A --> 0.7 and so on.

BR
Tom

**Comment by EckeFL** [comment]
Ich bekomme die die Werte aus openWB/chargepoint/3/get/evse_current gar nicht angezeigt in HA

In MQTT Explorer bekomme ich den Wert aber korrekt angezeigt. (Ein Faktor wird nicht benötigt)
@a529987659852 es wäre schön, wenn man den den Ladestrom per HA auch einstellen könnte.

**Comment by a529987659852** [comment]
Correction already implemented - will be available in next version

**Comment by EckeFL** [comment]
In Version 0.2 wird die Ladestromvorgabe jetzt bei mir weiterhin falsch angezeigt, ist um den Faktor 10 zu gering.
Im MQTT-Explorer wird es weiterhin korrekt angegeben. [Siehe oben.](https://github.com/a529987659852/openwb2mqtt/issues/6#issuecomment-1880147751) Allerdings wird der Wert nicht immer aktualisiert.
Anstecken im Modus Zielladen -> Wert (7) wird per MQTT übertragen. (Vermutlich weil der Wert durch oWB angepasst wurde)
Ändern auf Sofortladen -> Wert (16) wird übertragen.
Umstellen auf Zielladen -> Keine Übertragung
