### ISSUE TITLE
Fahrzeug Name in Dropdown

### ISSUE THREAD

**Issue by EckeFL** [a529987659852/openwb2mqtt#9]
Hallo, 

wäre es möglich die den Inhalt der sensor.openwb_chargepoint_n_fahrzeug Entität in das Fahrzeug Dropdown zu übernehmen?
Mit sensor.openwb_chargepoint_n_fahrzeug und sensor.openwb_chargepoint_n_fahrzeug_id hätte man dafür ja die dafür nötigen Werte, nachdem das Fahrzeug erstmalig augewählt wurde

**Comment by a529987659852** [comment]
Hi,
geht leider nicht, da die Werte des Drop-Downs beim Erzeugen der Entität gefüllt werden. Mir ist keine Methode bekannt, wie man diese nachträglich anpassen kann.
Ich bin auch nicht glücklich mit der Lösung, aber es ist das beste, was ich hinbekommen habe.

**Comment by EckeFL** [comment]
Was hältst von einer Möglichkeit, die Fahrzeuge im Rahmen der Konfiguration zu benennen? Dann könnte man die Liste auch auf die Länge der tatsächlich angelegten Fahrzeuge verkürzen.

**Comment by a529987659852** [comment]
Könnte man wahrscheinlich programmieren. Da ich aber nur ein EV habe, sehe ich momentan nicht die Notwendigkeit, dies zu implementieren.
